name: build and test

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
      - feature/infrastructure

jobs:
  build_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - windows-2019
          - macos-10.15
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cmake --preset ci ${{github.workspace}}
      - name: Build
        run: |
          cmake --build --preset ci
      - name: Test
        run: |
          ctest --preset ci
